### ISSUE TITLE
"* [roll] >10" shows error

### ISSUE THREAD

**Issue by ArcanaIreanol** [ExpeditionRPG/expedition-qdl#30]
according to the styleguide (https://github.com/ExpeditionRPG/expedition-quest-creator/blob/master/docs/style_guide.md#skill-checks), for a skill check we could use  `* [roll] > 10* for the button.
Problem: this will show an error in the quest editor.

I think the root cause is the following regex
https://github.com/ExpeditionRPG/expedition-qdl/blob/850f7e65c6a8780c7cacd9eb4a972a5567b84535/lib/Regex.tsx#L11

**Comment by toddmedema** [comment]
Looks like I need to update the documentation! The new syntax is to use `:icon:` instead of `[icon]` - the error message should describe that, but let me know if there's anything I can do to make the error message clearer :)

**Comment by toddmedema** [comment]
Closed by https://github.com/ExpeditionRPG/expedition-quest-creator/commit/38a02638498d4d6062c984a53389f3336bc1d9d6
