### ISSUE TITLE
Crawler should error if nodes are not reached

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-qdl#41]
Let's throw an error if we never reach a particular user node. Similar in concept to the "unreachable code" compile time error - users probably mean for their nodes to be used.

**Comment by toddmedema** [comment]
The only caveat I can see here is if someone has "note" nodes, ie parts of the story they want to add on later. But, we shouldn't be /encouraging/ that behavior (especially given that we provide people with the notes drawer), and in the future when we have multiple chapters / the ability to selectively publish chapters, that will entirely be not relevant.

That being said, perhaps we can state in the error details something along the lines of "If you intend to use this later, you can always cut and paste it into the "Quest Notes" tab on the bottom" (bonus effect: introduces more people to the notes tool)

**Comment by smartin015** [comment]
Backlogging for now.
