### ISSUE TITLE
Condensed schemas

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-qdl#75]
For objects we pass among the app, the api server, and the quest creator, we use several different definitions of the same general schemas (e.g. a typescript interface, joi validation, and sequelize schema for the same quest object). It'd be great to have a single place where such an object's parameters/validation/storage metadata is given that all repos could inherit.

**Comment by toddmedema** [comment]
Now we just have to use it in the app, qc and api :)
