### ISSUE TITLE
Unify tsconfig, tslint, webpack base configs

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-qdl#77]
We have *almost* the same config in the qdl, api, app, and admin repos. If we used a base template, we could reduce the amount of custom stuff we need to keep up to date in each of the repositories.

**Comment by smartin015** [comment]
Additional rules worth trying:

"no-magic-numbers": true,
"prefer-for-of": true,
"prefer-object-spread": true,

**Comment by toddmedema** [comment]
https://github.com/ExpeditionRPG/expedition/issues/61
